services:
  service:
    build: .
    restart: always
    depends_on:
      search:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - moviesnetwork

  search:
    image: krissmelikova/awesome_repository:v1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    healthcheck:
       test: curl -s http://fastapi-solutions-search-1:9200
       interval: 30s
       timeout: 10s
       retries: 50
    networks:
      - moviesnetwork

  cache:
    image: redis:7.2.4-alpine
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
     - ./redis-data:/var/lib/redis
    networks:
      - moviesnetwork

  nginx:
      image: nginx:1.25.4
      restart: always
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - service
      networks:
        - moviesnetwork


networks:
  moviesnetwork:
